export enum FeedbackType {
    GENERAL = 'GENERAL',
    BUG_REPORT = 'BUG_REPORT',
    FEATURE_REQUEST = 'FEATURE_REQUEST',
    CONTENT_ISSUE = 'CONTENT_ISSUE',
    COMMENT_REPORT = 'COMMENT_REPORT',
    OTHER = 'OTHER',
}
