CREATE TABLE IF NOT EXISTS "movies" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "movies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"tmdb_id" integer NOT NULL,
	"imdb_id" text NOT NULL,
	"adult" boolean DEFAULT false NOT NULL,
	"title" text NOT NULL,
	"poster_path" text,
	"backdrop_path" text,
	"budget" integer DEFAULT 0,
	"genres" jsonb NOT NULL,
	"homepage" text,
	"origin_country" jsonb NOT NULL,
	"original_language" text NOT NULL,
	"original_title" text NOT NULL,
	"overview" text NOT NULL,
	"production_companies" jsonb NOT NULL,
	"production_countries" jsonb NOT NULL,
	"release_date" date,
	"revenue" integer DEFAULT 0,
	"runtime" integer DEFAULT 0,
	"spoken_languages" jsonb NOT NULL,
	"status" text NOT NULL,
	"tag_line" text,
	"popularity" real DEFAULT 0,
	"vote_average" real DEFAULT 0,
	"vote_count" integer DEFAULT 0
);
