export { MoviesResolver } from './movies.resolver'
export { TitlesResolver } from './titles.resolver'
export { TvShowsResolver } from './tv-shows.resolver'
export { GenresResolver } from './genres.resolver'
export { LanguagesResolver } from './languages.resolver'
